# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hyseo <hyseo@student.42seoul.kr>           +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/02/20 09:55:53 by hyseo             #+#    #+#              #
#    Updated: 2022/03/22 18:48:35 by hyseo            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC	= c++
CFLAGS = -Wall -Werror -Wextra
RM	= rm -rf

NAME	= Materia
HEADER 	= AMateria.hpp	\
		Character.hpp	\
		Cure.hpp	\
		Ice.hpp		\
		ICharacter.hpp	\
		IMaterriaSource.hpp	\
		MateriaSource.hpp
OBJS	= AMateria.o	\
		Character.o	\
		Cure.o	\
		Ice.o		\
		MateriaSource.o	\
		main.o

all : $(NAME)

%.o : %.c $(HEADER) 
		$(CC) $(CFLAGS) -c $< -o $@

$(NAME) : $(OBJS) 
		$(CC) $(CFLAGS) -o $@ $^

clean : 
		$(RM) $(OBJS) *.replace

fclean : clean
		$(RM) $(NAME)

re : fclean all

.PHONY : clean fclean all
