# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hyseo <hyseo@student.42seoul.kr>           +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/02/20 09:55:53 by hyseo             #+#    #+#              #
#    Updated: 2022/03/07 20:52:53 by hyseo            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC	= c++
CFLAGS = -Wall -Werror -Wextra
RM	= rm -rf

NAME	= Animal
HEADER 	= Animal.hpp	\
		WrongAnimal.hpp	\
		Dog.hpp	\
		Cat.hpp	\
		WrongCat.hpp
OBJS	= Animal.o	\
		WrongAnimal.o	\
		Dog.o	\
		Cat.o	\
		WrongCat.o	\
		main.o	

all : $(NAME)

%.o : %.c $(HEADER) 
		$(CC) $(CFLAGS) -c $< -o $@

$(NAME) : $(OBJS) 
		$(CC) $(CFLAGS) -o $@ $^

clean : 
		$(RM) $(OBJS) *.replace

fclean : clean
		$(RM) $(NAME)

re : fclean all

.PHONY : clean fclean all
